---
title: "Non-Linear Models for the Plant Sciences"
author: "Claudio Dias da Silva Jr & Trevor Hefley"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
description: |
  An applied introduction to nonlinear models for the plant sciences, with
  emphasis on interpretation, uncertainty, and conscient implementation in R.
link-citations: yes
---

# About

This material is the base for the workshop **Nonlinear Models for the Plant Sciences** taught at Kansas State University on the Spring of 2026. This workshop was develop as a collaboration from the Department of Statistics, Department of Plant Pathology and the Institute for Digital Agriculture & Advanced Analytics (ID3A) as part of the [Advanced Analytics Workshops](https://www.k-state.edu/engagement/innovation-and-partnerships/interdisciplinary-institutes/digital-ag-advanced-analytics/about/events.html) series.

## Motivation

Non-linear models are widely used in plant sciences. Just like linear models, non-linear models can be fitted to data to enable statistical inference, which is required for scientific investigations and can aid when making management decisions. For example, logistic disease progression curves are a non-linear model used to understand plant disease epidemics, and statistical estimation and inference are needed to connect field data to management decisions (e.g., when to spray fungicide). “Non-Linear Models for the Plant Sciences” is designed to help you develop an understanding of non-linear models and how they fit data using common statistical techniques such as maximum likelihood estimation and Bayesian estimation. This workshop is co-hosted by the Departments of Statistics and Plant Pathology.
